import 'package:json_annotation/json_annotation.dart';

part 'message_dto.g.dart';

@JsonSerializable()
class MessageDTO {
  final String id;
  final String sender;
  final String recipient;
  final String content;
  final DateTime timestamp;

  bool isRead;
  DateTime? readTimestamp;

  bool isDelivered;
  DateTime? deliveredTimestamp;

  /// Ephemeral ID generated by the client (not the DB ID).
  String? clientTempId;

  MessageDTO({
    required this.id,
    required this.sender,
    required this.recipient,
    required this.content,
    required this.timestamp,
    this.isRead = false,
    this.readTimestamp,
    this.isDelivered = false,
    this.deliveredTimestamp,
    this.clientTempId,
  });

  factory MessageDTO.fromJson(Map<String, dynamic> json) =>
      _$MessageDTOFromJson(json);

  Map<String, dynamic> toJson() => _$MessageDTOToJson(this);
}
